# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: shanks的学习日志 # 标题
subtitle: shanks的学习日志 # 副标题
description: 这里记录了我的学习日志。
kewwords: shanks, 博客, mhyuan,mahy, hexo, hexo+github
author: shanks
language: zh-CN
timezone: Asia/Shanghai # 时区

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://mhynet.cn
host: mhynet.cn
# url: http://mhy-web.gitee.io/mhy-web.github.io/
root: /
# permalink: :year/:month/:day/:title/
# 优化SEO，减少URL层级结构
permalink: :title.html
permalink_defaults:
pretty_urls:
  trailing_index: true # 是否在永久链接中保留尾部的 index.html，设置为 false 时去除
  trailing_html: true # 是否在永久链接中保留尾部的 .html, 设置为 false 时去除 (对尾部的 index.html无效)

# Directory
source_dir: source # 资源文件夹，这个文件夹用来存放内容
public_dir: public # 公共文件夹，这个文件夹用于存放生成的站点文件
tag_dir: tags # 标签文件夹
archive_dir: archives # 归档文件夹
category_dir: categories # 分类文件夹
code_dir: downloads/code # Include code 文件夹，source_dir 下的子目录
i18n_dir: lang
#跳过source目录下文件的编译, 跳过指定文件的渲染，可使用glob表达式来匹配路径。
skip_render:
  - _test/*  # 两个 ** 表示该目录的所有下级目录, 但是两个**会报错，可能是主题里面的配置没有兼容
  - _data/*
  # - test/HTTP状态码.md
  # - test/数据结构与算法学习之排序.md

# stylus编译
stylus:
  compress: true

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: 2

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
# 排序方式 按写作时间排序
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  #order_by: -updated

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination 标记页码
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/

Plugins:
  hexo-generator-sitemap
  hexo-generator-feed
  hexo-generator-baidu-sitemap

#Feed Atom  SSR订阅
feed:
  type: atom
  path: atom.xml
  limit: 20

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: sitemap_mhynet.xml

## Themes: https://hexo.io/themes/
theme: yelee
# theme: BlueLake
# theme: volantis


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository:
    github: git@github.com:mhy-web/mhy-web.github.io.git # github
    gitee: git@gitee.com:mhy-web/mhy-web.git # 码云
  name: mhyuan
  email: dsz9258@163.com
  branch: master

# 添加本地搜索
## 默认本地搜索是用原生JS写的，但还需要HEXO插件创建的JSON数据文件配合。安装插件hexo-generator-json-content来创建JSON数据文件
jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: true
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true


# 主题的配置文件。在这里放置的配置会覆盖主题目录下的 _config.yml 中的配置
theme_config:
  beian:   # 备案
    enable: true
    key: 京ICP备19058010号 # 备案号
    link: http://www.beian.miit.gov.cn/ # 跳转到该地址
  baidu_tongji: b641a697cd393c453dcbbdfe0fefc625
  google_analytics: UA-155864731-1
  baidu_site: VJKBSS2rgO # 百度验证重新验证了，使用html标签验证 <meta name="baidu-site-verification" content="d3L7d33cpv" /> 或文件验证 baidu_verify_d3L7d33cpv.html
  google_site: OsZIswr6btG3y1q87keqlXy3VucMbYU6pBbnDVtNOB8 # <meta name="google-site-verification" content="OsZIswr6btG3y1q87keqlXy3VucMbYU6pBbnDVtNOB8" />
   # 百度、谷歌站长验证。填写 HTML 标签 content
  # Site Verification for Google and Baidu. HTML label content.
  # Show number of visitors of each article.
  # You can visit https://leancloud.cn to get AppID and AppKey.
  # AppID and AppKey are recommended to be the same as valine's for counter compatibility.
  # Do not enable both `valine.visitor` and `leancloud_visitors`.
  # yelee theme start
  leancloud_visitors:
    enable: true
    app_id: 1uREIRKwLhE57mcQ4jvraPBz-gzGzoHsz
    app_key: un7Isus45xOrp3Ih2zgfSNDr
    serverURLs: https://1ureirkw.lc-cn-n1-shared.com
    # Dependencies: https://github.com/theme-next/hexo-leancloud-counter-security
    # If you don't care about security in leancloud counter and just want to use it directly
    # (without hexo-leancloud-counter-security plugin), set `security` to `false`.
    security: false
    betterPerformance: false
    listShowCount: false # 首页列表是否显示阅读量
  # Valine
  # For more information: https://valine.js.org, https://github.com/xCss/Valine
  valine:
    enable: true
    appid: 1uREIRKwLhE57mcQ4jvraPBz-gzGzoHsz
    appkey: un7Isus45xOrp3Ih2zgfSNDr
    notify: true # Mail notifier
    verify: false # Verification code
    placeholder: Just go go # Comment box placeholder
    avatar: mm # Gravatar style
    guest_info: nick,mail,link # Custom comment header
    pageSize: 10 # Pagination size
    language: # Language, available values: en, zh-cn
    visitor: false # Article reading statistic
    comment_count: true # If false, comment count will only be displayed in post page, not in home page
    recordIP: true # Whether to record the commenter IP
    serverURLs: https://1ureirkw.lc-cn-n1-shared.com
  gitalk:
    enable: false
    shortname:
    owner: mhy-web # github 账户名
    admin: ['mhy-web']
    repo: blog-comment # 用来存放 issue 评论的仓库名（注意只需要写仓库名，不需要写完整的仓库地址）
    client_id: a717b97f95436ae1fce1
    client_secret: c864f5e20f3057474ae80373e63dfa405d552c57

  # gitment
  gitment:
    enable: false
    owner: mhy-web # github 账户名
    repo: blog-comment # 用来存放 issue 评论的仓库名（注意只需要写仓库名，不需要写完整的仓库地址）
    client_id: a717b97f95436ae1fce1
    client_secret: c864f5e20f3057474ae80373e63dfa405d552c57
    shortname:
  # 来必力(data-uid)
  livere:
    on: false
    data_uid: MTAyMC8zNDM1OS8xMDg5Ng== ## 来必力(data_uid)
  # end of yelee
